In [47]:
import pandas as pd
import numpy as np

In [41]:
df1 = pd.read_csv('C:/Users/yasin/Desktop/hotel_reviews.csv/hotel_reviews.csv')

In [42]:
df1

,Index,Name,Area,Review_Date,Rating_attribute,Rating(Out of 10),Review_Text
0,0,Hotel The Pearl,"Paharganj, New Delhi",Jul-23,Best budget friendly hotel,9.0,Hotel the pearl is perfect place to stay in De...
1,1,Hotel The Pearl,"Paharganj, New Delhi",Aug-23,Amazing place,9.0,Location of the hotel is perfect. The hotel is...
2,2,Hotel The Pearl,"Paharganj, New Delhi",Aug-23,Overall good stay. Economic.,9.0,"Location, Indian food."
3,3,Hotel The Pearl,"Paharganj, New Delhi",Aug-23,Lovely,9.0,The location and the hotel itself is great. Ne...
4,4,Hotel The Pearl,"Paharganj, New Delhi",Aug-23,Great hotel Great staff and great staying,9.0,Friendly and smiling staffs.. The reception st...
...,...,...,...,...,...,...,...
6996,6996,FabHotel F9 NSP,"North Delhi, New Delhi",Aug-23,I'd like to thank Manager.,10.0,"The room was good, comfortable and aesthetic \..."
6997,6997,FabHotel F9 NSP,"North Delhi, New Delhi",Jul-23,Superb,9.0,good hotel
6998,6998,FabHotel F9 NSP,"North Delhi, New Delhi",Jul-23,fabulous,10.0,good experience for me about hotel \nvery good...
6999,6999,FabHotel F9 NSP,"North Delhi, New Delhi",Jun-23,well done,10.0,well done
7000,7000,FabHotel F9 NSP,"North Delhi, New Delhi",Jul-23,Bad,2.0,Nothing

In [17]:
secilen_sutun = df["Review_Text"]

In [18]:
secilen_sutun

0       Hotel the pearl is perfect place to stay in De...
1       Location of the hotel is perfect. The hotel is...
2                                  Location, Indian food.
3       The location and the hotel itself is great. Ne...
4       Friendly and smiling staffs.. The reception st...
                              ...
6996    The room was good, comfortable and aesthetic \...
6997                                           good hotel
6998    good experience for me about hotel \nvery good...
6999                                            well done
7000                                              Nothing
Name: Review_Text, Length: 7001, dtype: object

In [53]:
restoran = pd.read_csv("C:/Users/yasin/Desktop/tripadvisor_hotel_reviews.csv/trip advisor restaurents  10k - trip_rest_neywork_1.csv")

In [55]:
restoran

,Title,Number of review,Catagory,Reveiw Comment,Popular food,Online Order
0,All Stars Sports Bar & Grill,21,"Bar, Pub","“The fries were terrific also, hot crisp...”",fries,Yes
1,Olio e Piu,"2,998","Italian, Pizza",“I love the food and our server Maria!”,filet mignon,Yes
2,Boucherie West Village,"1,465","French, Steakhouse",“The filet mignon was impeccable and the musse...,lobster,Yes
3,Club A Steakhouse,"4,413","American, Steakhouse",“My seafood cocktail had wonderful large lump ...,cacio e pepe,Yes
4,Piccola Cucina Estiatorio,403,"Italian, Sicilian",“penne al pomodoro and bucatini cacio e pepe w...,mussels,Yes
...,...,...,...,...,...,...
10392,The Sandwich Slut,No,"Mediterranean, Turkish",No,No,No
10393,The Sandwich Slut,No,"Mediterranean, Turkish",No,No,No
10394,The Sandwich Post,No,"Mediterranean, Turkish",No,No,No
10395,The Sandwich Cafe,No,"Mediterranean, Turkish",No,No,No
10396,Lezzet Mediterranean Turkish Restaurant,No,"Mediterranean, Turkish",No,No,No

In [54]:

restoran.columns

Index(['Title', 'Number of review', 'Catagory', 'Reveiw Comment',
       'Popular food', 'Online Order'],
      dtype='object')

In [58]:


yorum= restoran['Reveiw Comment']

In [59]:
yorum

0             “The fries were terrific also, hot crisp...”
1                  “I love the food and our server Maria!”
2        “The filet mignon was impeccable and the musse...
3        “My seafood cocktail had wonderful large lump ...
4        “penne al pomodoro and bucatini cacio e pepe w...
                               ...
10392                                                   No
10393                                                   No
10394                                                   No
10395                                                   No
10396                                                   No
Name: Reveiw Comment, Length: 10397, dtype: object

In [60]:
df_birlesik = pd.concat([yorum, secilen_sutun], ignore_index=True)  # ignore_index=True, indekslerin yeniden düzenlenmesini sağlar

In [61]:
df_birlesik

0             “The fries were terrific also, hot crisp...”
1                  “I love the food and our server Maria!”
2        “The filet mignon was impeccable and the musse...
3        “My seafood cocktail had wonderful large lump ...
4        “penne al pomodoro and bucatini cacio e pepe w...
                               ...
17393    The room was good, comfortable and aesthetic \...
17394                                           good hotel
17395    good experience for me about hotel \nvery good...
17396                                            well done
17397                                              Nothing
Length: 17398, dtype: object

In [62]:
df_birlesik.to_csv('birlesik_yorumlar.csv', index=False, encoding='utf-8')  # index=False, indeksin dosyaya yazılmasını engeller